name: sonic_frequencies
description: "A Flutter plugin for generating sounds at different frequencies."
version: 0.0.1
homepage: "https://github.com/SwanFlutter/sonic_frequencies"

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  plugin:
    platforms:
      android:
        package: com.example.sonic_frequencies
        pluginClass: SonicFrequenciesPlugin
      ios:
        pluginClass: SonicFrequenciesPlugin


